paths-ignore:
- README.md
- __pycache__/config.cpython-312.pyc
- __pycache__/config.cpython-313.pyc
- config.py
- core/__pycache__/github_scraper.cpython-312.pyc
- core/__pycache__/github_scraper.cpython-313.pyc
- core/__pycache__/matcher.cpython-312.pyc
- core/__pycache__/storage.cpython-312.pyc
- core/__pycache__/storage.cpython-313.pyc
- core/__pycache__/utils.cpython-312.pyc
- core/__pycache__/utils.cpython-313.pyc
- core/github_scraper.py
- core/matcher.py
- core/storage.py
- core/utils.py
- dashboard/app.py
- dashboard/templates/index.html
- data/backups/management.txt
- data/backups/results_backup@openai_0006.json
- data/backups/results_backup@openai_0007.json
- data/backups/results_backup_0001.json
- data/backups/results_backup_0002.json
- data/backups/results_backup_0003.json
- data/backups/results_backup_0004.json
- data/backups/results_backup_0005.json
- data/backups/tester.py
- data/results.json
- data/sample.json
- keys.json
- logs/activity.log
- main.py
- requirements.txt
- sandvox.py
- tested_results.json
- testopenai.py
- tests.py
- valid_apis.json
- valid_key_draft/mailgun@valid_apis.json
